name: Build Archive
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: emergent
        path: |
          main/mods
          main/config
          main/defaultconfig
          main/kubejs
          !main/.github
