name: Build Archive
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Release
      uses: thedoctor0/zip-release@0.7.0
      with: 
        filename: 'emergent.zip'
        type: 'zip'
        exclusions: 'README.md'
        
