name: Build Archive
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: emergent
        path: |
          Emergent/config/
          Emergent/defaultconfigs/
          Emergent/mods/
          Emergent/kubejs/
          !Emergent/.github/
